### ISSUE TITLE
return value RestResponse.response is a string instead of MyDict

### ISSUE THREAD

**Issue by yingyu-wang** [CiscoISE/ciscoisesdk#1]
![image](https://user-images.githubusercontent.com/60074904/121242210-24c92400-c851-11eb-8414-a0c587ff0006.png)

##### returned value RestResponse.response is a string instead of MyDict. Any idea?

**Comment by wastorga** [comment]
@yingyu-wang This issue seems to be related to the ISE ERS configuration rather than the SDK itself.

Check documentation to [Enable ERS (port 9060) ](https://developer.cisco.com/docs/identity-services-engine/3.0/#!setting-up/enable-ers-port-9060) for your ISE version.

Also, check in the ISE if you have API Gateway configured and set the `uses_api_gateway` accordingly.

If uses_api_gateway=True you just need to set the `base_url`.
If uses_api_gateway=False you need to set the `ui_base_url`, `ers_base_url`, `mnt_base_url` and `px_grid_base_url`.

**Comment by yingyu-wang** [comment]
Thank you @wastorga 
I tested this on ISE 2.6 with uses_api_gateway = False and manually specify the needed parameter, ers_base_url = https://ise-node:9060/ers.

**Comment by wastorga** [comment]
Glad to help.

In response, soon, we will improve the documentation to highlight the required setup to interact with the SDK.

**Comment by jbogarin** [comment]
@yingyu-wang I just wanted to highlight that although the SDK could work for versions prior to 3.1, it was developed and tested with 3.1 in mind and the official support is for 3.1
